"use strict";
import { MessageEmbed } from "discord.js";

export default {
	name: "help",
	aliases: ["help", "helpme", "cmdhelp", "commands", "cmds"],
	description: "*helps* you?",
	usage: "<command: ?string>",
	async run(client, message, args) {
		if (args.length) {
			const command = client.commands.get(args[0].toLowerCase()) || client.commands.find(cmd => cmd.aliases && cmd.aliases.includes(args[0].toLowerCase()));
			if (!command) return message.reply(`A command by that name/alias was not found. Take a look in \`${message.guild ? message.guild.prefix : client.const.prefix}help\` for a list of existing commnads.`);

			return message.reply({
				embeds: [
					new MessageEmbed()
						.setColor(message.author.color)
						.setAuthor({ name: message.author.tag, iconURL: message.author.displayAvatarURL({ dynamic: true }) })
						.setTitle(`Command: \`${message.guild ? message.guild.prefix : client.const.prefix}${command.name}\``)
						.setDescription(command.description)
						.addField("Aliases", command.aliases.join(", "), true)
						.addField("Category", client.utils.capital(command.category), true)
						.addField("Usage", `\`\`\`\n${message.guild?.prefix || client.const.prefix}${command.name} ${command.usage || ""}\n\`\`\``),
				],
			});
		}
		const context = new MessageEmbed()
			.setTitle(`${client.user.username} Help`)
			.setColor(message.author.color)
			.setDescription(`
${client.user.username} is a bot designed by ${client.users.cache.get(client.const.display).tag} who (evidently) has no friends.
			`)
			.addField("Invite Me", `You can invite me to your server by clicking [here](${client.const.ssInvite}, "invite ${client.user.username}").`)
			.addField("Keywords", `For a list of keywords that the bot will automatically replace with their corresponding values, see \`${message.guild ? message.guild.prefix : client.const.prefix}kw\`.`)
			.addField("Privacy Policy", "The bot does not store **ANY** sensitive data outside of the context of this bot. The only type of data that will be stored is numbers generated by your progress within the bot (such as your balance), along with the odd exception (such as your bio). In addition to this, logs of previously-run commands may be stored for debugging purposes.");
		const commands = new MessageEmbed()
			.setTitle("Command Help")
			.setColor(message.author.color)
			.setDescription(`Here are some commands which can be used by members, arranged in categories. You may use \`${message.guild ? message.guild.prefix : client.const.prefix}help <command name>\` for some extra information on a certain command.`);

		client.const.commandCategories.forEach(cat => {
			commands.addField(`${client.utils.capital(cat)} Commands`, client.commands.filter(cmd => cmd.category === cat).map(({ name }) => `\`${name}\``).join(", "));
		});
		message.reply({
			embeds: [
				context,
				commands,
			],
		});
	},
};